# -*- coding: utf-8 -*-
"""MLminiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BA3lpX5a0tvbfS64y_ihc4aUv4TwoihV
"""

import cv2
import matplotlib.pyplot as plt

configpath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weigthpath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weigthpath, configpath)

classLabels=[]
file_name='labels.txt'
with open(file_name,'rt') as ftp:
  classLabels=ftp.read().rstrip('\n').split('\n')

print(classLabels)

net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127,5,127.5))
net.setInputSwapRB(True)

img=cv2.imread('car.jpg')
plt.imshow(img)

ClassIndex, confidece, bbox= net.detect(img, confThreshold=0.5)

print(ClassIndex)

font_scale=2.5
font=cv2.FONT_HERSHEY_PLAIN
for ClassInd,conf,boxes in zip(ClassIndex.flatten(),confidece.flatten(),bbox):
  cv2.rectangle(img,boxes,(255,0,0),3)
  cv2.putText(img, classLabels[ClassInd - 1], (boxes[0]+10, boxes[1]+40), font, fontScale=font_scale, color=(0,0,255), thickness=3)

plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))